config/routes.rb
Rails.application.routes.draw do
  root "campaigns#index"
  devise_for :users, :controllers => {
    registrations: 'registrations'
}

  

  concern :commentable do
    resources :comments
  end

  resources :campaigns, concerns: :commentable do
    resources :todos
    resources :topics, concerns: :commentable
  end

  resources :experts,:novices



  

end

app/models/topic.rb
class Topic < ApplicationRecord
    validates :title, presence: true, length: { minimum: 3 }, format: {with: /[a-zA-Z]/}
    validate :user_allowed

    has_many :comments, as: :commentable
    belongs_to :campaign
    belongs_to :topic_creator, polymorphic: true
    

    def user_allowed
        if campaign.expert.campaigns.joins(:topics).where(topics: {topic_creator_id: topic_creator.id}).any?
            errors.add(:base, "Not Allowed")
        end
    end
    
end

                # error.add("You have already created a topic for campaigns belonging to this Expert")

app/controllers/topics_controller.rb
class TopicsController < ApplicationController


    before_action :find_campaign, only: [:index, :new,:create, :find_topic]
    before_action :find_topic, only: [:edit, :update, :show,:destroy]
    
    def index
        @topics = @campaign.topics.all
    end
    
    def new
        @topic = @campaign.topics.new
    end

    def show
    end
    

    def create 
        @topic = @campaign.topics.new(topic_params)
        authorize @topic
        @topic.topic_creator = current_user
        if @topic.save
          flash[:success] = "Object successfully created"
          redirect_to campaign_topics_path(@campaign)
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
    end

    def edit
        authorize @topic
    end

    def update
        authorize @topic
        if @topic.update(topic_params)
          flash[:success] = "Object was successfully updated"
          redirect_to campaign_topic_path(@campaign,@topic)
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end

    def destroy
        authorize @topic
        if @topic.destroy
            flash[:success] = 'Object was successfully deleted.'
            redirect_to campaign_topics_path(@campaign)
        else
            flash[:error] = 'Something went wrong'
            redirect_to campaign_topics_path(@campaign)
        end
    end

    def find_campaign
        @campaign = Campaign.find(params[:campaign_id])      
    end
    
    def find_topic
        @campaign = Campaign.find(params[:campaign_id])
        @topic = @campaign.topics.find(params[:id]) 
    end

    private

    def topic_params
        params.require(:topic).permit(:title)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with model: [@campaign, @topic] do |f| %>  
  
  <div class="form-group row mt-5">
        <%= f.label :title, class:"col-sm-2 col-form-label"  %>

    <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control",placeholder:"Title"  %>
    </div>
  </div>
  

  <div class="form-group row">
    <div class="col-sm-10">
    <% if @topic.persisted? %>
        <%= f.submit "Update" , class:"btn btn-dark" %>      
    <% else %>
        <%= f.submit "Create" , class:"btn btn-dark" %>      
      <% end %>
    </div>
  </div>

<% end %>

app/views/topics/edit.html.erb
<div class="signup_container container">
<div class="text-center my-2">
 <h2 class="page_heading">Edit Topic</h2>
</div>
<%= render 'form' %>


</div>

app/views/topics/index.html.erb
<div class="container">
    <div class="text-center my-2">
        <h2 class="page_heading">Discussion Topics</h2>
    </div>
    <table class="table table-striped table-hover table-responsive-sm index_table">
  <thead class="thead-dark">
    <tr class="table_row">
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Comments</th>
      <th scope="col">Created By</th>
    </tr>
  </thead>
  <tbody>
  <% @topics.each_with_index do |topic, index|%>                    
    <tr class="table_row">
      <th scope="row"><%= index %></th>
      <td><%= link_to topic.title.capitalize, [@campaign,topic] ,id:"index_links"%></td>
      <td class="px-5"><%= topic.comments.count %></td>
      <td class="px-5"><%= topic.topic_creator.username.capitalize %></td>
    </tr>
    <% end %>
  </tbody>
  
</table>
<% if policy(@topics).create? %>
    <div class="col">
        <%= link_to 'Add Topic', new_campaign_topic_path(@campaign),class:"btn btn-outline-dark btn-sm mx-1" ,  role:"button" %>
    </div>
  <% end %>
</div>





       
       
        

app/views/topics/new.html.erb
<div class="signup_container container">
<div class="text-center my-2">
 <h2 class="page_heading">New Topic</h2>
</div><%= render 'form' %>

app/views/topics/show.html.erb
<div class="container">
    <div class="mt-5">
        <h3 class="pt-3">Discussion Topic</h3>
<p class="mt-4"><strong>Title: <%= @topic.title %></strong></p>
<p><strong>Created by: <%= @topic.topic_creator.username.capitalize %></strong></p>


<% if policy(@topic).edit? && policy(@topic).destroy?  %>
    <div>
<%= link_to "🖋", edit_campaign_topic_path(@campaign,@topic),id:"action_edit" %><%= link_to "🗑", campaign_topic_path(@campaign,@topic),id:"action_delete", method: :delete,
                  data: { confirm: "Are you sure?" } %>

</div>
<% end %>


<div class="mt-5"><h5>Comments: <%= @topic.comments.count %></h5></div>

<div class="container my-3 pb-4">


</div>

<%= render @topic.comments %>

<div class="row my-4 ">
<%= render 'comments/form', locals: {commentable: @topic, type:"Topic"} %>
</div>
</div>
</div>

</div>