config/routes.rb
Rails.application.routes.draw do
  root "campaigns#index"
  devise_for :users, :controllers => {
    registrations: 'registrations'
}

  

  concern :commentable do
    resources :comments
  end

  resources :campaigns, concerns: :commentable do
    resources :todos
    resources :topics, concerns: :commentable
  end

  resources :experts,:novices



  

end

app/models/todo.rb
class Todo < ApplicationRecord
    
    validates :description, presence: true, length: { minimum: 3 }, format: {with: /[a-zA-Z]/}
    
    belongs_to :campaign
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

    before_action :find_campaign, only: [:index, :new, :create, :find_todo]
    before_action :find_todo, only: [:edit, :update, :show,:destroy]
    
    def index
        @todos = @campaign.todos.all
    end
    
    def new
        @todo = @campaign.todos.new
    end

    def show
    end
    

    def create
        
        
        @todo = @campaign.todos.new(todo_params)
        authorize @todo
        if @todo.save
          flash[:success] = "Object successfully created"
          redirect_to campaign_path(@campaign)
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
    end

    def edit
        authorize @todo
    end

    def update
        authorize @todo
        if @todo.update(todo_params)
          flash[:success] = "Object was successfully updated"
          redirect_to @campaign
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end

    def destroy
        authorize @todo
        if @todo.destroy
            flash[:success] = 'Object was successfully deleted.'
            redirect_to @campaign
        else
            flash[:error] = 'Something went wrong'
            redirect_to todos_url
        end
    end

    def find_campaign
        @campaign = Campaign.find(params[:campaign_id])      
    end
    
    def find_todo
        @campaign = Campaign.find(params[:campaign_id])
        @todo = @campaign.todos.find(params[:id]) 
    end

    private

    def todo_params
        params.require(:todo).permit(:description,:completed,:campaign_id)
    end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= form_with model: [@campaign, @todo] do |f| %>  
  
  <div class="form-group row mt-5">
        <%= f.label :description, class:"col-sm-2 col-form-label"  %>

    <div class="col-sm-10">
        <%= f.text_field :description, class: "form-control",placeholder:"Description"  %>
    </div>
  </div>
  
  <div class="form-group row mt-5">
        <%= f.label :completed, class: "col-sm-2 col-form-label" %>

    <div class="col-sm-10">
        <%= f.check_box :completed, class: "form-check-input mx-2" %>

    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
    <% if @todo.persisted? %>
        <%= f.submit "Update" , class:"btn btn-dark" %>    

    <% else %>
        <%= f.submit "Create" , class:"btn btn-dark" %>      
  
      <% end %>
    </div>
  </div>

<% end %>

app/views/todos/_show.html.erb
<div class="container" id="todos_container">
    <div class="container mb-4" id="todo_headings">
    <div class="row mx-4">
    <div class="col-5 offset-2 ">
    <h5>Description</h5>
    
    </div>

    <div class="col-3">
    <h5>Completed</h5>
     </div>
     
    <%# <div class="col-3" >
    <h5 id="action">Action</h5>
    </div> %>
</div>
</div>
<ol>
<% @campaign.todos.each do |todo| %>
        <div class="container" id="todo_content">
            <div class="row mx-1">
                <div class="col-5 offset-2">
                    <p><%= todo.description %></p>
                </div>

                <div class="col-3" >
                    <%if todo.completed %>
                            <p id="status_true">✔</p>
                       <% else %>
                           <p id="status_false">✖</p>         
                       <% end %>
                </div>

                     
                    <div class="col-1"  >
                            <%= link_to "🖋", edit_campaign_todo_path(@campaign,todo),id:"action_edit" if policy(todo).edit?%>

                            <%= link_to "🗑", [@campaign,todo],id:"action_delete",
                        method: :delete,
                        data: {confirm: "Are you sure?"} if policy(todo).destroy?%>
        
                </div>
            </div>
        </div>
<% end %>
</ol>

    

             <% if current_user.id==@campaign.user_id %>
             <div class="row my-2">
                <div class="col offset-2">
                    <%= link_to "Add todo", new_campaign_todo_path(@campaign),class:"btn btn-outline-dark btn-sm " ,id:"btn" , role:"button"  %>
                </div>
            </div>
<% end %>           
</div>






 

app/views/todos/edit.html.erb
<div class="signup_container container">
<div class="text-center my-2">
 <h2 class="page_heading">Edit Todo</h2>
</div>
<%= render 'form' %>

app/views/todos/index.html.erb
<h1><%= @user.name.capitalize() + "'s" %> Tasks</h1>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Description&nbsp;&nbsp;|&nbsp;&nbsp;Completed&nbsp;&nbsp;|&nbsp;&nbsp;Action</h4>
<ul>
<% @tasks.each do |task| %>
    <li>
        <p><%= task.description %>&nbsp;&nbsp;|&nbsp;&nbsp;
        <%if task.completed %>
            ✔
        <% else %>
            ✖           
        <% end %>&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;

        <%= link_to "Edit", edit_task_path(task)%>&nbsp;|
        <%= link_to "Delete", task,
         method: :delete,
         data: {confirm: "Are you sure?"}
         %>
        </p>
    </li>
<% end %>
</ul>
<br/>

<%= link_to  "Add Task", :new_user_task %>

app/views/todos/new.html.erb
<div class="signup_container container">
<div class="text-center my-2">
 <h2 class="page_heading">New Todo</h2>
</div>
<%= render 'form' %>