config/routes.rb
Rails.application.routes.draw do
  root "campaigns#index"
  devise_for :users, :controllers => {
    registrations: 'registrations'
}

  

  concern :commentable do
    resources :comments
  end

  resources :campaigns, concerns: :commentable do
    resources :todos
    resources :topics, concerns: :commentable
  end

  resources :experts,:novices



  

end

app/models/campaign.rb
class Campaign < ApplicationRecord
    
    enum estimated_duration: [ :within_1_week, :within_1_month, :within_3_months]


    validates :title, presence: true, length: { minimum: 3 }, format: {with: /[a-zA-Z]/}
    validates :purpose, presence: true, length: { minimum: 3 }, format: {with: /[a-zA-Z]/}
    validates :estimated_duration, inclusion: { in: estimated_durations.keys }

    
    has_many :comments, as: :commentable ,dependent: :destroy
    has_many :todos, dependent: :destroy
    has_many :topics, dependent: :destroy
    belongs_to :expert, class_name: "User", foreign_key: :user_id
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
    def index
        @campaigns = Campaign.all
    end
    
    def new
        
        authorize @campaign = Campaign.new

    end

    def show
        @campaign = Campaign.find(params[:id])
    end
    

    def create
        @campaign = Campaign.new(campaign_params)
        authorize @campaign
        @campaign.user_id = current_user.id
        if @campaign.save
          flash[:success] = "Object successfully created"
          redirect_to @campaign
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
    end

    def edit
        authorize @campaign = Campaign.find(params[:id])
    end

    def update
        authorize @campaign = Campaign.find(params[:id])
        if @campaign.update(campaign_params)
          flash[:success] = "Object was successfully updated"
          redirect_to @campaign
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end

    def destroy
        authorize @campaign = Campaign.find(params[:id])
        if @campaign.destroy
            flash[:success] = 'Object was successfully deleted.'
            redirect_to campaigns_url
        else
            flash[:error] = 'Something went wrong'
            redirect_to campaigns_url
        end
    end

    private
        def campaign_params
        params.require(:campaign).permit(:title,:purpose,:estimated_duration)
        end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= form_with model: campaign do |f| %>
  
  <div class="form-group row mt-5">
        <%= f.label :title, class:"col-sm-2 col-form-label"  %>

    <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control",placeholder:"Title"  %>
    </div>
  </div>
  
  <div class="form-group row  ">
        <%= f.label :purpose, class:"col-sm-2 col-form-label"  %>
    <div class="col-sm-10">
        <%= f.text_field :purpose, class: "form-control",placeholder:"Purpose"  %>
    </div>
  </div>

  <div class="form-group row  ">
        <%= f.label :estimated_duration, class:"col-sm-2 col-form-label"  %>
    <div class="col-sm-10">
        <%= f.select :estimated_duration, Campaign.estimated_durations.keys, {}, class:'form-control' %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-sm-10">
    <% if campaign.persisted? %>
        <%= f.submit "Update" , class:"btn btn-dark" %>      
    <% else %>
        <%= f.submit "Create" , class:"btn btn-dark" %>      
      <% end %>
    </div>
  </div>

<% end %>
</div>

app/views/campaigns/edit.html.erb
<div class="signup_container container">
<div class="text-center my-2">
 <h2 class="page_heading">Edit Campaign</h2>
</div>


<%= render 'form', campaign: @campaign %>

app/views/campaigns/index.html.erb
<div class="container">
    <div class="text-center my-2">
        <h2 class="page_heading">Campaigns</h2>
    </div>
    <table class="table table-striped table-hover table-responsive-sm index_table">
  <thead class="thead-dark">
    <tr class="table_row">
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Purpose</th>
      <th scope="col">Created By</th>
    </tr>
  </thead>
  <tbody>
  <% @campaigns.each_with_index do |campaign, index|%>                    
    <tr class="table_row">
      <th scope="row"><%= index %></th>
      <td><%= link_to campaign.title.capitalize, campaign ,id:"index_links"%></td>
      <td><%= campaign.purpose %></td>
      <td><%= campaign.expert.username %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% if policy(@campaigns).create? %> <div class="col"> <%= link_to 'Add Campaign', :new_campaign,class:"btn btn-outline-dark btn-sm mx-1" ,  role:"button" %> </div> <% end %>
</div>

app/views/campaigns/new.html.erb
<div class="signup_container container">
<div class="text-center my-2">
 <h2 class="page_heading">New Campaign</h2>
</div>

<%= render 'form', campaign: @campaign %>

app/views/campaigns/show.html.erb
<div class="container my-5">

    <div class="row ">
        <div class="col-8"><h2><%= @campaign.title.upcase%></h2>
        <%= link_to "🖋", :edit_campaign,id:"action_edit" if policy(@campaign).edit?%><%= link_to "🗑", :campaign,id:"action_delete", method: :delete,
                  data: { confirm: "Are you sure?" } if policy(@campaign).edit?%>
        </div>

        
    </div>

    <div class="row  mt-5">
        <div class="col">
             <h6 >Purpose: <%= @campaign.purpose.capitalize %></h6>
        </div>

        <div class="col">
            <h6>Created by: <%= @campaign.expert.username %></h6>    
        </div>

        <div class="col">
            <h6>Duration: <%= @campaign.estimated_duration %></h6>    
        </div>

        <div class="col">
            <strong><%= link_to 'DISCUSSIONS', campaign_topics_path(@campaign) ,id: "index_links" %></strong>
        </div>

    </div>

</div>


<div>




</div>

<%= render 'todos/show'%>

<div class="container my-5 pb-4">
<div class="row my-4 mx-1"><h5>Comments: <%= @campaign.comments.count %></h5></div>

<%= render @campaign.comments %>

<div class="row my-4 ">
    <%= render 'comments/form' , locals: {commentable: @campaign, type: "Campaign"}%>
</div>

</div>